### ISSUE TITLE
DomainLockDown.ps1 - error

### ISSUE THREAD

**Issue by snyper82** [curi0usJack/activedirectory#3]
I'm getting this while running the script:
Method invocation failed because [System.Object[]] doesn't contain a method nam
ed 'Contains'.
At C:\Users\administrator.MP\DomainLockDown.ps1:328 char:26
- if (($dcsnetbios.Contains <<<< ($m) -eq $false) -and ($dcsfq.Contains($m) -eq
  $false)) {
  - CategoryInfo          : InvalidOperation: (Contains:String) [], RuntimeE
    xception
    - FullyQualifiedErrorId : MethodNotFound

I'm not great at PS so any help would be wonderful!

**Comment by curi0usJack** [comment]
Hmm - either $dcsnetbios or $dcsfq is null, which shouldn't be. I'm
suspecting a DNS issue or AD misconfiguration, but it's hard to tell (could
also just be lousy programming on my part :-).

Run this code as DA on the DC that you're running DomainLockDown on. All it
does is check to make sure the AD cmdlets are properly enumerating your
domain. Save it as a .ps1 file and execute. Post back the results.

---

Import-Module ActiveDirectory
$domain = Get-ADDomain $env:USERDOMAIN
$dcsnetbios = $domain.ReplicaDirectoryServers | %{$_.Trim($domain.DNSRoot)}

if ($domain -eq $null) {Write-Host "Domain is null"}
if ($domain.ReplicaDirectoryServers -eq $null) {Write-Host "DC list is
null"}
if ($domain.DNSRoot -eq $null) { Write-Host "DNS Root is null"}
if ($dcsnetbios -eq $null) {Write-Host "DCSNetBios is null"}

Write-Host "Done"

---

**Comment by snyper82** [comment]
That is running it on a DC as DA.  I still get the results, but not sure if I'm missing anything because of error.
I'll post back

**Comment by snyper82** [comment]
I've ran it 3 times and I'm getting different results each time... 

No biggie I have a few things on it to correct, which is what I'm looking for (reviewing the video from DerbyCon, enjoyed the presentation and reviewing to work on implementing).

**Comment by curi0usJack** [comment]
Sounds good. Let me know how it goes! Oh - and did you see the extra code I sent you to run? It will check the variables that are used in the error you posted.

**Comment by snyper82** [comment]
I did not, but have now.

I ran it and "Done"

**Comment by curi0usJack** [comment]
hmm. You said you're getting different outputs every time? would be
interested in seeing some of the results. Tricky though, cuz I doubt you
want to post any of your AD vulns on github. ;-).

Can always shoot me an email at curi0usjack@gmail.com if you want to
troubleshoot further.

**Comment by snyper82** [comment]
That email doesn't exist?

**Comment by curi0usJack** [comment]
Lame. Sorry about that. I forgot the one that matches my handle was already
taken.

Correct one: curi0sJack@gmail.com
